package vista;

import modelo.Postulante;
import controlador.Aplicacion;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.RutInvalidoException;

/*
    Para asignar el texto de los campos a un Postulante, hay que declarar primero
    las variables "auxiliares" debajo del public class PostularView.
    Luego, cada private void FieldXXXXActionPerformed, almacena el texto
    escrito en su rectángulo dentro de la variable asignada.
*/
public class PostularView extends javax.swing.JFrame {
    private int rut;
    private String nombre;
    private int edad;
    private String hab1;
    private String hab2;
    private String hab3;
    private String jornada;
    private int experiencia;
    private String correo;
    private String puesto;
    
    /**
     * Creates new form PostularView
     */
    public PostularView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public int obtenerValor(javax.swing.JFormattedTextField field){
        int auxiliar;
        String auxTexto = field.getText();
        try{
            auxiliar = Integer.parseInt(auxTexto);
        }catch(Exception a){
            throw new RutInvalidoException("Rut contiene caracteres o está vacío.");
        }
        if (auxTexto.length() > 8){
            throw new RutInvalidoException("Rut no debe tener digito verificador.");
        }
        return auxiliar;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BotonPostular = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ComboPuesto = new javax.swing.JComboBox<>();
        FieldRut = new javax.swing.JFormattedTextField();
        FieldNombre = new javax.swing.JFormattedTextField();
        FieldEdad = new javax.swing.JFormattedTextField();
        FieldExperiencia = new javax.swing.JFormattedTextField();
        FieldJornada = new javax.swing.JFormattedTextField();
        FieldCorreo = new javax.swing.JFormattedTextField();
        FieldHab1 = new javax.swing.JFormattedTextField();
        FieldHab2 = new javax.swing.JFormattedTextField();
        FieldHab3 = new javax.swing.JFormattedTextField();
        BotonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setText("Rut:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Edad:");

        jLabel5.setText("Experiencia:");

        jLabel6.setText("Jornada:");

        jLabel7.setText("Habilidad 1:");

        jLabel8.setText("Habilidad 2:");

        jLabel9.setText("Habilidad 3:");

        BotonPostular.setText("Postular");
        BotonPostular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPostularActionPerformed(evt);
            }
        });

        jLabel10.setText("rut sin digito verificador ni puntos");

        jLabel11.setText("nombre_apellido");

        jLabel12.setText("años");

        jLabel13.setText("años");

        jLabel14.setText("fulltime o partime");

        jLabel15.setText("Correo: ");

        jLabel16.setText("Puesto: ");

        ComboPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPuestoActionPerformed(evt);
            }
        });

        FieldRut.setActionCommand("<Not Set>");
        FieldRut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldRutFocusLost(evt);
            }
        });

        FieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldNombreFocusLost(evt);
            }
        });

        FieldEdad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldEdadFocusLost(evt);
            }
        });

        FieldExperiencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldExperienciaFocusLost(evt);
            }
        });

        FieldJornada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldJornadaFocusLost(evt);
            }
        });

        FieldCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldCorreoFocusLost(evt);
            }
        });

        FieldHab1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldHab1FocusLost(evt);
            }
        });

        FieldHab2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldHab2FocusLost(evt);
            }
        });

        FieldHab3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldHab3FocusLost(evt);
            }
        });

        BotonRegresar.setText("Regresar");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(BotonPostular)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(16, 16, 16))
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(21, 21, 21)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)))
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(ComboPuesto, 0, 226, Short.MAX_VALUE)
                            .addComponent(FieldRut)
                            .addComponent(FieldNombre)
                            .addComponent(FieldEdad)
                            .addComponent(FieldExperiencia)
                            .addComponent(FieldJornada)
                            .addComponent(FieldCorreo)
                            .addComponent(FieldHab1)
                            .addComponent(FieldHab2)
                            .addComponent(FieldHab3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FieldRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(FieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(FieldExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(FieldJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(FieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ComboPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(FieldHab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldHab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(FieldHab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonPostular)
                    .addComponent(BotonRegresar))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonPostularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPostularActionPerformed
        // TODO add your handling code here:
        /*
            La idea es que cuando este botón se aprete, se debe crear un postulante
            con la información guardada en las variables auxiliares y luego agregar
            al Postulante generado a los mapas generales del controlador Aplicacion.java
            
        */
        Postulante p = new Postulante(nombre, rut, edad, experiencia, jornada, correo, puesto);
        p.agregarHabilidad(hab1);
        p.agregarHabilidad(hab2);
        p.agregarHabilidad(hab3);
        Aplicacion.getInstancia().agregarPostulante(p);
        JOptionPane.showMessageDialog(null,"Postulando...");
        /*
            Aplicacion.getInstancia() nos permite utilizar las funciones dentro de
            la clase Aplicacion.java, pudiendo acceder a los HashMap generales.
        */
    }//GEN-LAST:event_BotonPostularActionPerformed

    private void ComboPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPuestoActionPerformed
        puesto = (String) ComboPuesto.getSelectedItem();
    }//GEN-LAST:event_ComboPuestoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        llenarCombo();
    }//GEN-LAST:event_formWindowOpened

    private void FieldRutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldRutFocusLost
        try{
            rut = obtenerValor(FieldRut);
        }catch(RutInvalidoException a){
            JOptionPane.showMessageDialog(null,a.getMensaje());
            FieldRut.setText("");
        }
    }//GEN-LAST:event_FieldRutFocusLost

    private void FieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldNombreFocusLost
        nombre = FieldNombre.getText();
    }//GEN-LAST:event_FieldNombreFocusLost

    private void FieldEdadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldEdadFocusLost
        edad = Integer.parseInt(FieldEdad.getText());
    }//GEN-LAST:event_FieldEdadFocusLost

    private void FieldExperienciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldExperienciaFocusLost
        experiencia = Integer.parseInt(FieldExperiencia.getText());
    }//GEN-LAST:event_FieldExperienciaFocusLost

    private void FieldJornadaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldJornadaFocusLost
        jornada = FieldJornada.getText();
    }//GEN-LAST:event_FieldJornadaFocusLost

    private void FieldCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldCorreoFocusLost
        correo = FieldCorreo.getText();
    }//GEN-LAST:event_FieldCorreoFocusLost

    private void FieldHab1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldHab1FocusLost
        hab1 = FieldHab1.getText();
    }//GEN-LAST:event_FieldHab1FocusLost

    private void FieldHab2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldHab2FocusLost
        hab2 = FieldHab2.getText();
    }//GEN-LAST:event_FieldHab2FocusLost

    private void FieldHab3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldHab3FocusLost
        hab3 = FieldHab3.getText();
    }//GEN-LAST:event_FieldHab3FocusLost

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        controlador.PostularController.eliminar();
        controlador.MenuPersonaController.mostrar();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    public void llenarCombo(){
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel();
        
        for(int i = 0 ; i < Aplicacion.getInstancia().conseguirTrabajos().size() ; i++){
            model.addElement(Aplicacion.getInstancia().conseguirTrabajos().get(i).getNombre());
        }
        
        ComboPuesto.setModel(model);
        ComboPuesto.setSelectedIndex(0);
        
        puesto = (String) ComboPuesto.getSelectedItem();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostularView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostularView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostularView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostularView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostularView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonPostular;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JComboBox<String> ComboPuesto;
    private javax.swing.JFormattedTextField FieldCorreo;
    private javax.swing.JFormattedTextField FieldEdad;
    private javax.swing.JFormattedTextField FieldExperiencia;
    private javax.swing.JFormattedTextField FieldHab1;
    private javax.swing.JFormattedTextField FieldHab2;
    private javax.swing.JFormattedTextField FieldHab3;
    private javax.swing.JFormattedTextField FieldJornada;
    private javax.swing.JFormattedTextField FieldNombre;
    private javax.swing.JFormattedTextField FieldRut;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
